import yaml
from datetime import datetime
import argparse
from utils import get_dirs




def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="evotest_parallel.py",
        description="run different modes of random and evo testing for ripple.",
    )

    parser.add_argument(
        "--ripple-image",
        type=str,
        default="xrpllabsofficial/xrpld:2.6.0",
        metavar="RIPPLE_IMAGE",
        help="the docker image to use for the rippled instances (default: xrpllabsofficial/xrpld:2.6.0)",
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=98,
        metavar="SEED",
        help="the random seed",
    )

    parser.add_argument(
        "--min-delay-ms",
        type=int,
        default=0,
        metavar="MIN_DELAY_MS",
        help="the minimum delay in milliseconds (default: 0)",
    )

    parser.add_argument(
        "--max-delay-ms",
        type=int,
        default=100,
        metavar="MAX_DELAY_MS",
        help="the maximum delay in milliseconds (default: 100)",
    )

    parser.add_argument(
        "--rust-log-level",
        type=str,
        default="info",
        choices=["trace", "debug", "info", "warn", "error"],
        metavar="RUST_LOG_LEVEL",
        help="the log level for Rust code (default: info)",
    )

    parser.add_argument(
        "--byzz-min-seq",
        type=int,
        default=5,
        metavar="BYZZ_MIN_SEQ",
        help="starting seq to perform byzz behavior (default: 5)",
    )

    parser.add_argument(
        "--byzz-max-seq",
        type=int,
        default=10,
        metavar="BYZZ_MAX_SEQ",
        help="ending seq to perform byzz behavior (default: 10)",
    )

    parser.add_argument(
        "--max-ledger-seq",
        type=int,
        default=15,
        metavar="MAX_LEDGER_SEQ",
        help="the maximum ledger sequence number to run the tests (default: 15)",
    )

    parser.add_argument(
        "--total-num-tests",
        type=int,
        default=500,
        metavar="TOTAL_NUM_TESTS",
        help="the total number of tests to run (default: 500)",
    )

    parser.add_argument(
        "--population-size",
        type=int,
        default=10,
        metavar="POPULATION_SIZE",
        help="the population size only used for the evolutionary algorithm (default: 10)",
    )

    parser.add_argument(
        "--fitness-function",
        type=str,
        default="mean_validation_time",
        choices=[
            "num_propose_set",
            "num_getledger_hashes",
            "num_getledger_messages",
            "mean_validation_time",
            "var_validation_time",
            "validation_distribution_entropy",
            "message_entropy_integral",
            "message_entropy_average",
            "markov_matrix_non_similarity",
        ],
        metavar="FITNESS_FUNCTION",
        help="the fitness function to use only for the evolutionary algorithm (default: mean_validation_time)",
    )

    parser.add_argument(
        "--strategy",
        type=str,
        choices=["EvoDelayStrategy", "RandomDelayByzzStrategy", "RandomByzzStrategy", "RandomDelayStrategy"],   
        default="EvoDelayStrategy",
        metavar="STRATEGY",
        help="the name of the rocket_controller strategy class to use (e.g. EvoDelayStrategy)",
    )

    parser.add_argument(
        "--max-parallel-workers",
        type=int,
        default=1,
        metavar="MAX_PARALLEL_WORKERS",
        help="the maximum number of parallel workers to use for running tests (default: 1)",
    )

    parser.add_argument(
        "--base-network-config-yaml",
        type=str,
        default="network.yaml",
        metavar="NETWORK_BASE_CONFIG_YAML",
        help="the YAML file for (base) network configuration (default: network.yaml)",
    )

    parser.add_argument(
        "--mu",
        type=int,
        default=4,
        metavar="MU",
        help="the number of offspring to produce in each generation for the evolutionary algorithm (default: 4)",
    )

    parser.add_argument(
        "--timeout-per-seq",
        type=int,
        default=30,
        metavar="TIMEOUT_PER_SEQ",
        help="the timeout in seconds for each ledger sequence (default: 30)",
    )

    parser.add_argument(
        "--individual-timeout-sec",
        type=int,
        default=300,
        metavar="IND_TIMEOUT",
        help="maximum number of seconds allowed for one individual evaluation (default: 300)",
    )

    # run identifier allows multiple evotest_parallel instances to run in same
    # workspace without container name collisions.  It is prepended to each
    # instance_id generated by the evolution code and also to validator
    # container names via ValidatorNode.get_container_name().
    parser.add_argument(
        "--run-id",
        type=str,
        default="",
        metavar="RUN_ID",
        help="a short prefix used to isolate containers/ports when running "
        "multiple experiments in parallel",
    )

    # Port overrides / offsets.  These permit the caller to shift the base
    # ports defined in the network YAML, ensuring that two concurrent
    # experiments don't accidentally expose services on the same host port.
    # note: individual offsets for each instance are calculated inside
    # evotest_parallel (port_offset = idx % max_workers).  no global offset
    # should be supplied by the user; instead, provide explicit base port
    # values below or use the grpc-base-port argument.

    parser.add_argument(
        "--base-port-peer",
        type=int,
        metavar="BASE_PORT_PEER",
        help="override the base_peer port in the network configuration",
    )
    parser.add_argument(
        "--base-port-ws",
        type=int,
        metavar="BASE_PORT_WS",
        help="override the base_ws port in the network configuration",
    )
    parser.add_argument(
        "--base-port-ws-admin",
        type=int,
        metavar="BASE_PORT_WS_ADMIN",
        help="override the base_ws_admin port in the network configuration",
    )
    parser.add_argument(
        "--base-port-rpc",
        type=int,
        metavar="BASE_PORT_RPC",
        help="override the base_rpc port in the network configuration",
    )

    # ``run_id`` doubles as the log directory identifier.  if you supply a
    # non-empty string it will be prepended to container names *and* used
    # as the top-level folder name under ``logs/``; otherwise a timestamp is
    # generated automatically.

    parser.add_argument(
        "--grpc-base-port",
        type=int,
        default=50051,
        metavar="GRPC_BASE_PORT",
        help="the starting gRPC port; each instance will add its own offset",
    )

    return parser.parse_args()


def extend_configs(args: argparse.Namespace) -> dict:
    configs = vars(args)
    dirs = get_dirs(__file__)
    configs = {**configs, **dirs}

    _start_datetime = datetime.now().strftime("%Y_%m_%d_%Hh%Mm_%Ss")

    with open(configs["cur_dir"] / configs["base_network_config_yaml"], "r") as f:
        network_config = yaml.safe_load(f)
        # apply CLI overrides for base ports if provided
        for key in [
            ("base_port_peer", "base_port_peer"),
            ("base_port_ws", "base_port_ws"),
            ("base_port_ws_admin", "base_port_ws_admin"),
            ("base_port_rpc", "base_port_rpc"),
        ]:
            cli_name, cfg_name = key
            if configs.get(cli_name) is not None:
                network_config[cfg_name] = configs[cli_name]

        configs["base_network_config"] = network_config
        configs["number_of_nodes"] = network_config.get("number_of_nodes")
        configs["byzz_nodes"] = network_config.get("byzz_nodes")

    # 推导max_generation
    configs["max_generation"] = configs["total_num_tests"] // configs["population_size"]

    # the CLI names ``min_delay_ms``/``max_delay_ms`` are used directly by
    # the evolution code; no further translation is required.

    # logging directories already computed above

    # determine the identifier used for the top‑level log directory.  if the
    # caller supplied a run_id it serves both as the container-prefix and the
    # name of the parent folder under ``logs``; otherwise we fall back to the
    # current datetime.  we don't create any extra intermediate keys.
    if configs.get("run_id"):
        identifier = configs["run_id"]
    else:
        identifier = datetime.now().strftime("%Y_%m_%d_%Hh%Mm_%Ss")

    # final per-strategy directory = logs/<identifier>/<strategy>/
    parent = configs["logs_dir"] / identifier
    configs["test_log_dir"] = parent / str(configs.get("strategy", ""))

    return configs


def get_configs() -> dict:
    args = parse_args()
    return extend_configs(args)


if __name__ == "__main__":
    configs = get_configs()
    for key, value in configs.items():
        print(f"{key}: {value}. ({type(value)})")
