"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Packet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    FROM_PORT_FIELD_NUMBER: builtins.int
    TO_PORT_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    from_port: builtins.int
    to_port: builtins.int
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        from_port: builtins.int = ...,
        to_port: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "data", b"data", "from_port", b"from_port", "to_port", b"to_port"
        ],
    ) -> None: ...

global___Packet = Packet

@typing.final
class PacketAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    ACTION_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    action: builtins.int
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        action: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["action", b"action", "data", b"data"]
    ) -> None: ...

global___PacketAck = PacketAck

@typing.final
class ValidatorNodeInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PEER_PORT_FIELD_NUMBER: builtins.int
    WS_PUBLIC_PORT_FIELD_NUMBER: builtins.int
    WS_ADMIN_PORT_FIELD_NUMBER: builtins.int
    RPC_PORT_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    VALIDATION_KEY_FIELD_NUMBER: builtins.int
    VALIDATION_PRIVATE_KEY_FIELD_NUMBER: builtins.int
    VALIDATION_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    VALIDATION_SEED_FIELD_NUMBER: builtins.int
    peer_port: builtins.int
    ws_public_port: builtins.int
    ws_admin_port: builtins.int
    rpc_port: builtins.int
    status: builtins.str
    validation_key: builtins.str
    validation_private_key: builtins.str
    validation_public_key: builtins.str
    validation_seed: builtins.str
    def __init__(
        self,
        *,
        peer_port: builtins.int = ...,
        ws_public_port: builtins.int = ...,
        ws_admin_port: builtins.int = ...,
        rpc_port: builtins.int = ...,
        status: builtins.str = ...,
        validation_key: builtins.str = ...,
        validation_private_key: builtins.str = ...,
        validation_public_key: builtins.str = ...,
        validation_seed: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "peer_port",
            b"peer_port",
            "rpc_port",
            b"rpc_port",
            "status",
            b"status",
            "validation_key",
            b"validation_key",
            "validation_private_key",
            b"validation_private_key",
            "validation_public_key",
            b"validation_public_key",
            "validation_seed",
            b"validation_seed",
            "ws_admin_port",
            b"ws_admin_port",
            "ws_public_port",
            b"ws_public_port",
        ],
    ) -> None: ...

global___ValidatorNodeInfo = ValidatorNodeInfo

@typing.final
class ValidatorNodeInfoAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.str
    def __init__(
        self,
        *,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___ValidatorNodeInfoAck = ValidatorNodeInfoAck
