"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Packet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    FROM_PORT_FIELD_NUMBER: builtins.int
    TO_PORT_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    from_port: builtins.int
    to_port: builtins.int
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        from_port: builtins.int = ...,
        to_port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "from_port", b"from_port", "to_port", b"to_port"]) -> None: ...

global___Packet = Packet

@typing.final
class PacketAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    ACTION_FIELD_NUMBER: builtins.int
    SEND_AMOUNT_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    action: builtins.int
    send_amount: builtins.int
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        action: builtins.int = ...,
        send_amount: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["action", b"action", "data", b"data", "send_amount", b"send_amount"]) -> None: ...

global___PacketAck = PacketAck

@typing.final
class ValidatorNodeInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PEER_PORT_FIELD_NUMBER: builtins.int
    WS_PUBLIC_PORT_FIELD_NUMBER: builtins.int
    WS_ADMIN_PORT_FIELD_NUMBER: builtins.int
    RPC_PORT_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    VALIDATION_KEY_FIELD_NUMBER: builtins.int
    VALIDATION_PRIVATE_KEY_FIELD_NUMBER: builtins.int
    VALIDATION_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    VALIDATION_SEED_FIELD_NUMBER: builtins.int
    peer_port: builtins.int
    ws_public_port: builtins.int
    ws_admin_port: builtins.int
    rpc_port: builtins.int
    status: builtins.str
    validation_key: builtins.str
    validation_private_key: builtins.str
    validation_public_key: builtins.str
    validation_seed: builtins.str
    def __init__(
        self,
        *,
        peer_port: builtins.int = ...,
        ws_public_port: builtins.int = ...,
        ws_admin_port: builtins.int = ...,
        rpc_port: builtins.int = ...,
        status: builtins.str = ...,
        validation_key: builtins.str = ...,
        validation_private_key: builtins.str = ...,
        validation_public_key: builtins.str = ...,
        validation_seed: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["peer_port", b"peer_port", "rpc_port", b"rpc_port", "status", b"status", "validation_key", b"validation_key", "validation_private_key", b"validation_private_key", "validation_public_key", b"validation_public_key", "validation_seed", b"validation_seed", "ws_admin_port", b"ws_admin_port", "ws_public_port", b"ws_public_port"]) -> None: ...

global___ValidatorNodeInfo = ValidatorNodeInfo

@typing.final
class ValidatorNodeInfoAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.str
    def __init__(
        self,
        *,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___ValidatorNodeInfoAck = ValidatorNodeInfoAck

@typing.final
class GetConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetConfig = GetConfig

@typing.final
class Partition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODES_FIELD_NUMBER: builtins.int
    @property
    def nodes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        nodes: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nodes", b"nodes"]) -> None: ...

global___Partition = Partition

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BASE_PORT_PEER_FIELD_NUMBER: builtins.int
    BASE_PORT_WS_FIELD_NUMBER: builtins.int
    BASE_PORT_WS_ADMIN_FIELD_NUMBER: builtins.int
    BASE_PORT_RPC_FIELD_NUMBER: builtins.int
    NUMBER_OF_NODES_FIELD_NUMBER: builtins.int
    NET_PARTITIONS_FIELD_NUMBER: builtins.int
    UNL_PARTITIONS_FIELD_NUMBER: builtins.int
    base_port_peer: builtins.int
    base_port_ws: builtins.int
    base_port_ws_admin: builtins.int
    base_port_rpc: builtins.int
    number_of_nodes: builtins.int
    @property
    def net_partitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Partition]: ...
    @property
    def unl_partitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Partition]: ...
    def __init__(
        self,
        *,
        base_port_peer: builtins.int = ...,
        base_port_ws: builtins.int = ...,
        base_port_ws_admin: builtins.int = ...,
        base_port_rpc: builtins.int = ...,
        number_of_nodes: builtins.int = ...,
        net_partitions: collections.abc.Iterable[global___Partition] | None = ...,
        unl_partitions: collections.abc.Iterable[global___Partition] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["base_port_peer", b"base_port_peer", "base_port_rpc", b"base_port_rpc", "base_port_ws", b"base_port_ws", "base_port_ws_admin", b"base_port_ws_admin", "net_partitions", b"net_partitions", "number_of_nodes", b"number_of_nodes", "unl_partitions", b"unl_partitions"]) -> None: ...

global___Config = Config
