"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MessageType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MessageTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MessageType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    mtMANIFESTS: _MessageType.ValueType  # 2
    mtPING: _MessageType.ValueType  # 3
    mtCLUSTER: _MessageType.ValueType  # 5
    mtENDPOINTS: _MessageType.ValueType  # 15
    mtTRANSACTION: _MessageType.ValueType  # 30
    mtGET_LEDGER: _MessageType.ValueType  # 31
    mtLEDGER_DATA: _MessageType.ValueType  # 32
    mtPROPOSE_LEDGER: _MessageType.ValueType  # 33
    mtSTATUS_CHANGE: _MessageType.ValueType  # 34
    mtHAVE_SET: _MessageType.ValueType  # 35
    mtVALIDATION: _MessageType.ValueType  # 41
    mtGET_OBJECTS: _MessageType.ValueType  # 42
    mtGET_SHARD_INFO: _MessageType.ValueType  # 50
    mtSHARD_INFO: _MessageType.ValueType  # 51
    mtGET_PEER_SHARD_INFO: _MessageType.ValueType  # 52
    mtPEER_SHARD_INFO: _MessageType.ValueType  # 53
    mtVALIDATORLIST: _MessageType.ValueType  # 54
    mtSQUELCH: _MessageType.ValueType  # 55
    mtVALIDATORLISTCOLLECTION: _MessageType.ValueType  # 56
    mtPROOF_PATH_REQ: _MessageType.ValueType  # 57
    mtPROOF_PATH_RESPONSE: _MessageType.ValueType  # 58
    mtREPLAY_DELTA_REQ: _MessageType.ValueType  # 59
    mtREPLAY_DELTA_RESPONSE: _MessageType.ValueType  # 60

class MessageType(_MessageType, metaclass=_MessageTypeEnumTypeWrapper):
    """Unused numbers in the list below may have been used previously. Please don't
    reassign them for reuse unless you are 100% certain that there won't be a
    conflict. Even if you're sure, it's probably best to assign a new type.
    """

mtMANIFESTS: MessageType.ValueType  # 2
mtPING: MessageType.ValueType  # 3
mtCLUSTER: MessageType.ValueType  # 5
mtENDPOINTS: MessageType.ValueType  # 15
mtTRANSACTION: MessageType.ValueType  # 30
mtGET_LEDGER: MessageType.ValueType  # 31
mtLEDGER_DATA: MessageType.ValueType  # 32
mtPROPOSE_LEDGER: MessageType.ValueType  # 33
mtSTATUS_CHANGE: MessageType.ValueType  # 34
mtHAVE_SET: MessageType.ValueType  # 35
mtVALIDATION: MessageType.ValueType  # 41
mtGET_OBJECTS: MessageType.ValueType  # 42
mtGET_SHARD_INFO: MessageType.ValueType  # 50
mtSHARD_INFO: MessageType.ValueType  # 51
mtGET_PEER_SHARD_INFO: MessageType.ValueType  # 52
mtPEER_SHARD_INFO: MessageType.ValueType  # 53
mtVALIDATORLIST: MessageType.ValueType  # 54
mtSQUELCH: MessageType.ValueType  # 55
mtVALIDATORLISTCOLLECTION: MessageType.ValueType  # 56
mtPROOF_PATH_REQ: MessageType.ValueType  # 57
mtPROOF_PATH_RESPONSE: MessageType.ValueType  # 58
mtREPLAY_DELTA_REQ: MessageType.ValueType  # 59
mtREPLAY_DELTA_RESPONSE: MessageType.ValueType  # 60
global___MessageType = MessageType

class _TransactionStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TransactionStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TransactionStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    tsNEW: _TransactionStatus.ValueType  # 1
    """origin node did/could not validate"""
    tsCURRENT: _TransactionStatus.ValueType  # 2
    """scheduled to go in this ledger"""
    tsCOMMITED: _TransactionStatus.ValueType  # 3
    """in a closed ledger"""
    tsREJECT_CONFLICT: _TransactionStatus.ValueType  # 4
    tsREJECT_INVALID: _TransactionStatus.ValueType  # 5
    tsREJECT_FUNDS: _TransactionStatus.ValueType  # 6
    tsHELD_SEQ: _TransactionStatus.ValueType  # 7
    tsHELD_LEDGER: _TransactionStatus.ValueType  # 8
    """held for future ledger"""

class TransactionStatus(_TransactionStatus, metaclass=_TransactionStatusEnumTypeWrapper):
    """A transaction can have only one input and one output.
    If you want to send an amount that is greater than any single address of yours
    you must first combine coins from one address to another.
    """

tsNEW: TransactionStatus.ValueType  # 1
"""origin node did/could not validate"""
tsCURRENT: TransactionStatus.ValueType  # 2
"""scheduled to go in this ledger"""
tsCOMMITED: TransactionStatus.ValueType  # 3
"""in a closed ledger"""
tsREJECT_CONFLICT: TransactionStatus.ValueType  # 4
tsREJECT_INVALID: TransactionStatus.ValueType  # 5
tsREJECT_FUNDS: TransactionStatus.ValueType  # 6
tsHELD_SEQ: TransactionStatus.ValueType  # 7
tsHELD_LEDGER: TransactionStatus.ValueType  # 8
"""held for future ledger"""
global___TransactionStatus = TransactionStatus

class _NodeStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _NodeStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_NodeStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    nsCONNECTING: _NodeStatus.ValueType  # 1
    """acquiring connections"""
    nsCONNECTED: _NodeStatus.ValueType  # 2
    """convinced we are connected to the real network"""
    nsMONITORING: _NodeStatus.ValueType  # 3
    """we know what the previous ledger is"""
    nsVALIDATING: _NodeStatus.ValueType  # 4
    """we have the full ledger contents"""
    nsSHUTTING: _NodeStatus.ValueType  # 5
    """node is shutting down"""

class NodeStatus(_NodeStatus, metaclass=_NodeStatusEnumTypeWrapper): ...

nsCONNECTING: NodeStatus.ValueType  # 1
"""acquiring connections"""
nsCONNECTED: NodeStatus.ValueType  # 2
"""convinced we are connected to the real network"""
nsMONITORING: NodeStatus.ValueType  # 3
"""we know what the previous ledger is"""
nsVALIDATING: NodeStatus.ValueType  # 4
"""we have the full ledger contents"""
nsSHUTTING: NodeStatus.ValueType  # 5
"""node is shutting down"""
global___NodeStatus = NodeStatus

class _NodeEvent:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _NodeEventEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_NodeEvent.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    neCLOSING_LEDGER: _NodeEvent.ValueType  # 1
    """closing a ledger because its close time has come"""
    neACCEPTED_LEDGER: _NodeEvent.ValueType  # 2
    """accepting a closed ledger, we have finished computing it"""
    neSWITCHED_LEDGER: _NodeEvent.ValueType  # 3
    """changing due to network consensus"""
    neLOST_SYNC: _NodeEvent.ValueType  # 4

class NodeEvent(_NodeEvent, metaclass=_NodeEventEnumTypeWrapper): ...

neCLOSING_LEDGER: NodeEvent.ValueType  # 1
"""closing a ledger because its close time has come"""
neACCEPTED_LEDGER: NodeEvent.ValueType  # 2
"""accepting a closed ledger, we have finished computing it"""
neSWITCHED_LEDGER: NodeEvent.ValueType  # 3
"""changing due to network consensus"""
neLOST_SYNC: NodeEvent.ValueType  # 4
global___NodeEvent = NodeEvent

class _TxSetStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TxSetStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TxSetStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    tsHAVE: _TxSetStatus.ValueType  # 1
    """We have this set locally"""
    tsCAN_GET: _TxSetStatus.ValueType  # 2
    """We have a peer with this set"""
    tsNEED: _TxSetStatus.ValueType  # 3
    """We need this set and can't get it"""

class TxSetStatus(_TxSetStatus, metaclass=_TxSetStatusEnumTypeWrapper): ...

tsHAVE: TxSetStatus.ValueType  # 1
"""We have this set locally"""
tsCAN_GET: TxSetStatus.ValueType  # 2
"""We have a peer with this set"""
tsNEED: TxSetStatus.ValueType  # 3
"""We need this set and can't get it"""
global___TxSetStatus = TxSetStatus

class _TMLedgerInfoType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TMLedgerInfoTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TMLedgerInfoType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    liBASE: _TMLedgerInfoType.ValueType  # 0
    """basic ledger info"""
    liTX_NODE: _TMLedgerInfoType.ValueType  # 1
    """transaction node"""
    liAS_NODE: _TMLedgerInfoType.ValueType  # 2
    """account state node"""
    liTS_CANDIDATE: _TMLedgerInfoType.ValueType  # 3
    """candidate transaction set"""

class TMLedgerInfoType(_TMLedgerInfoType, metaclass=_TMLedgerInfoTypeEnumTypeWrapper): ...

liBASE: TMLedgerInfoType.ValueType  # 0
"""basic ledger info"""
liTX_NODE: TMLedgerInfoType.ValueType  # 1
"""transaction node"""
liAS_NODE: TMLedgerInfoType.ValueType  # 2
"""account state node"""
liTS_CANDIDATE: TMLedgerInfoType.ValueType  # 3
"""candidate transaction set"""
global___TMLedgerInfoType = TMLedgerInfoType

class _TMLedgerType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TMLedgerTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TMLedgerType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ltACCEPTED: _TMLedgerType.ValueType  # 0
    ltCURRENT: _TMLedgerType.ValueType  # 1
    """no longer supported"""
    ltCLOSED: _TMLedgerType.ValueType  # 2

class TMLedgerType(_TMLedgerType, metaclass=_TMLedgerTypeEnumTypeWrapper): ...

ltACCEPTED: TMLedgerType.ValueType  # 0
ltCURRENT: TMLedgerType.ValueType  # 1
"""no longer supported"""
ltCLOSED: TMLedgerType.ValueType  # 2
global___TMLedgerType = TMLedgerType

class _TMQueryType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TMQueryTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TMQueryType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    qtINDIRECT: _TMQueryType.ValueType  # 0

class TMQueryType(_TMQueryType, metaclass=_TMQueryTypeEnumTypeWrapper): ...

qtINDIRECT: TMQueryType.ValueType  # 0
global___TMQueryType = TMQueryType

class _TMReplyError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TMReplyErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TMReplyError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    reNO_LEDGER: _TMReplyError.ValueType  # 1
    """We don't have the ledger you are asking about"""
    reNO_NODE: _TMReplyError.ValueType  # 2
    """We don't have any of the nodes you are asking for"""
    reBAD_REQUEST: _TMReplyError.ValueType  # 3
    """The request is wrong, e.g. wrong format"""

class TMReplyError(_TMReplyError, metaclass=_TMReplyErrorEnumTypeWrapper): ...

reNO_LEDGER: TMReplyError.ValueType  # 1
"""We don't have the ledger you are asking about"""
reNO_NODE: TMReplyError.ValueType  # 2
"""We don't have any of the nodes you are asking for"""
reBAD_REQUEST: TMReplyError.ValueType  # 3
"""The request is wrong, e.g. wrong format"""
global___TMReplyError = TMReplyError

class _TMLedgerMapType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TMLedgerMapTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TMLedgerMapType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    lmTRANASCTION: _TMLedgerMapType.ValueType  # 1
    """transaction map"""
    lmACCOUNT_STATE: _TMLedgerMapType.ValueType  # 2
    """account state map"""

class TMLedgerMapType(_TMLedgerMapType, metaclass=_TMLedgerMapTypeEnumTypeWrapper): ...

lmTRANASCTION: TMLedgerMapType.ValueType  # 1
"""transaction map"""
lmACCOUNT_STATE: TMLedgerMapType.ValueType  # 2
"""account state map"""
global___TMLedgerMapType = TMLedgerMapType

@typing.final
class TMManifest(google.protobuf.message.Message):
    """------------------------------------------------------------------------------

    Provides the current ephemeral key for a validator.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOBJECT_FIELD_NUMBER: builtins.int
    stobject: builtins.bytes
    """A Manifest object in the Ripple serialization format."""
    def __init__(
        self,
        *,
        stobject: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["stobject", b"stobject"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["stobject", b"stobject"]) -> None: ...

global___TMManifest = TMManifest

@typing.final
class TMManifests(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LIST_FIELD_NUMBER: builtins.int
    HISTORY_FIELD_NUMBER: builtins.int
    history: builtins.bool
    """The manifests sent when a peer first connects to another peer are `history`."""
    @property
    def list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TMManifest]: ...
    def __init__(
        self,
        *,
        list: collections.abc.Iterable[global___TMManifest] | None = ...,
        history: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["history", b"history"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["history", b"history", "list", b"list"]) -> None: ...

global___TMManifests = TMManifests

@typing.final
class TMClusterNode(google.protobuf.message.Message):
    """------------------------------------------------------------------------------

    The status of a node in our cluster
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLICKEY_FIELD_NUMBER: builtins.int
    REPORTTIME_FIELD_NUMBER: builtins.int
    NODELOAD_FIELD_NUMBER: builtins.int
    NODENAME_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    publicKey: builtins.str
    reportTime: builtins.int
    nodeLoad: builtins.int
    nodeName: builtins.str
    address: builtins.str
    def __init__(
        self,
        *,
        publicKey: builtins.str | None = ...,
        reportTime: builtins.int | None = ...,
        nodeLoad: builtins.int | None = ...,
        nodeName: builtins.str | None = ...,
        address: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address", "nodeLoad", b"nodeLoad", "nodeName", b"nodeName", "publicKey", b"publicKey", "reportTime", b"reportTime"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "nodeLoad", b"nodeLoad", "nodeName", b"nodeName", "publicKey", b"publicKey", "reportTime", b"reportTime"]) -> None: ...

global___TMClusterNode = TMClusterNode

@typing.final
class TMLoadSource(google.protobuf.message.Message):
    """Sources that are placing load on the server"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    COST_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    name: builtins.str
    cost: builtins.int
    count: builtins.int
    """number of connections"""
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        cost: builtins.int | None = ...,
        count: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cost", b"cost", "count", b"count", "name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cost", b"cost", "count", b"count", "name", b"name"]) -> None: ...

global___TMLoadSource = TMLoadSource

@typing.final
class TMCluster(google.protobuf.message.Message):
    """The status of all nodes in the cluster"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLUSTERNODES_FIELD_NUMBER: builtins.int
    LOADSOURCES_FIELD_NUMBER: builtins.int
    @property
    def clusterNodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TMClusterNode]: ...
    @property
    def loadSources(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TMLoadSource]: ...
    def __init__(
        self,
        *,
        clusterNodes: collections.abc.Iterable[global___TMClusterNode] | None = ...,
        loadSources: collections.abc.Iterable[global___TMLoadSource] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["clusterNodes", b"clusterNodes", "loadSources", b"loadSources"]) -> None: ...

global___TMCluster = TMCluster

@typing.final
class TMGetShardInfo(google.protobuf.message.Message):
    """Request info on shards held"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOPS_FIELD_NUMBER: builtins.int
    LASTLINK_FIELD_NUMBER: builtins.int
    PEERCHAIN_FIELD_NUMBER: builtins.int
    hops: builtins.int
    """number of hops to travel"""
    lastLink: builtins.bool
    """true if last link in the peer chain"""
    @property
    def peerchain(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """IDs used to route messages"""

    def __init__(
        self,
        *,
        hops: builtins.int | None = ...,
        lastLink: builtins.bool | None = ...,
        peerchain: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["hops", b"hops", "lastLink", b"lastLink"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["hops", b"hops", "lastLink", b"lastLink", "peerchain", b"peerchain"]) -> None: ...

global___TMGetShardInfo = TMGetShardInfo

@typing.final
class TMShardInfo(google.protobuf.message.Message):
    """Info about shards held"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHARDINDEXES_FIELD_NUMBER: builtins.int
    NODEPUBKEY_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    LASTLINK_FIELD_NUMBER: builtins.int
    PEERCHAIN_FIELD_NUMBER: builtins.int
    shardIndexes: builtins.str
    """rangeSet of shard indexes"""
    nodePubKey: builtins.bytes
    """The node's public key"""
    endpoint: builtins.str
    """ipv6 or ipv4 address"""
    lastLink: builtins.bool
    """true if last link in the peer chain"""
    @property
    def peerchain(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """IDs used to route messages"""

    def __init__(
        self,
        *,
        shardIndexes: builtins.str | None = ...,
        nodePubKey: builtins.bytes | None = ...,
        endpoint: builtins.str | None = ...,
        lastLink: builtins.bool | None = ...,
        peerchain: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["endpoint", b"endpoint", "lastLink", b"lastLink", "nodePubKey", b"nodePubKey", "shardIndexes", b"shardIndexes"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["endpoint", b"endpoint", "lastLink", b"lastLink", "nodePubKey", b"nodePubKey", "peerchain", b"peerchain", "shardIndexes", b"shardIndexes"]) -> None: ...

global___TMShardInfo = TMShardInfo

@typing.final
class TMLink(google.protobuf.message.Message):
    """Node public key"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODEPUBKEY_FIELD_NUMBER: builtins.int
    nodePubKey: builtins.bytes
    """node public key"""
    def __init__(
        self,
        *,
        nodePubKey: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["nodePubKey", b"nodePubKey"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["nodePubKey", b"nodePubKey"]) -> None: ...

global___TMLink = TMLink

@typing.final
class TMGetPeerShardInfo(google.protobuf.message.Message):
    """Request info on shards held"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOPS_FIELD_NUMBER: builtins.int
    LASTLINK_FIELD_NUMBER: builtins.int
    PEERCHAIN_FIELD_NUMBER: builtins.int
    hops: builtins.int
    """number of hops to travel"""
    lastLink: builtins.bool
    """true if last link in the peer chain"""
    @property
    def peerChain(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TMLink]:
        """public keys used to route messages"""

    def __init__(
        self,
        *,
        hops: builtins.int | None = ...,
        lastLink: builtins.bool | None = ...,
        peerChain: collections.abc.Iterable[global___TMLink] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["hops", b"hops", "lastLink", b"lastLink"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["hops", b"hops", "lastLink", b"lastLink", "peerChain", b"peerChain"]) -> None: ...

global___TMGetPeerShardInfo = TMGetPeerShardInfo

@typing.final
class TMPeerShardInfo(google.protobuf.message.Message):
    """Info about shards held"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHARDINDEXES_FIELD_NUMBER: builtins.int
    NODEPUBKEY_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    LASTLINK_FIELD_NUMBER: builtins.int
    PEERCHAIN_FIELD_NUMBER: builtins.int
    shardIndexes: builtins.str
    """rangeSet of shard indexes"""
    nodePubKey: builtins.bytes
    """node public key"""
    endpoint: builtins.str
    """ipv6 or ipv4 address"""
    lastLink: builtins.bool
    """true if last link in the peer chain"""
    @property
    def peerChain(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TMLink]:
        """public keys used to route messages"""

    def __init__(
        self,
        *,
        shardIndexes: builtins.str | None = ...,
        nodePubKey: builtins.bytes | None = ...,
        endpoint: builtins.str | None = ...,
        lastLink: builtins.bool | None = ...,
        peerChain: collections.abc.Iterable[global___TMLink] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["endpoint", b"endpoint", "lastLink", b"lastLink", "nodePubKey", b"nodePubKey", "shardIndexes", b"shardIndexes"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["endpoint", b"endpoint", "lastLink", b"lastLink", "nodePubKey", b"nodePubKey", "peerChain", b"peerChain", "shardIndexes", b"shardIndexes"]) -> None: ...

global___TMPeerShardInfo = TMPeerShardInfo

@typing.final
class TMTransaction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RAWTRANSACTION_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    RECEIVETIMESTAMP_FIELD_NUMBER: builtins.int
    DEFERRED_FIELD_NUMBER: builtins.int
    rawTransaction: builtins.bytes
    status: global___TransactionStatus.ValueType
    receiveTimestamp: builtins.int
    deferred: builtins.bool
    """not applied to open ledger"""
    def __init__(
        self,
        *,
        rawTransaction: builtins.bytes | None = ...,
        status: global___TransactionStatus.ValueType | None = ...,
        receiveTimestamp: builtins.int | None = ...,
        deferred: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["deferred", b"deferred", "rawTransaction", b"rawTransaction", "receiveTimestamp", b"receiveTimestamp", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["deferred", b"deferred", "rawTransaction", b"rawTransaction", "receiveTimestamp", b"receiveTimestamp", "status", b"status"]) -> None: ...

global___TMTransaction = TMTransaction

@typing.final
class TMStatusChange(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NEWSTATUS_FIELD_NUMBER: builtins.int
    NEWEVENT_FIELD_NUMBER: builtins.int
    LEDGERSEQ_FIELD_NUMBER: builtins.int
    LEDGERHASH_FIELD_NUMBER: builtins.int
    LEDGERHASHPREVIOUS_FIELD_NUMBER: builtins.int
    NETWORKTIME_FIELD_NUMBER: builtins.int
    FIRSTSEQ_FIELD_NUMBER: builtins.int
    LASTSEQ_FIELD_NUMBER: builtins.int
    newStatus: global___NodeStatus.ValueType
    newEvent: global___NodeEvent.ValueType
    ledgerSeq: builtins.int
    ledgerHash: builtins.bytes
    ledgerHashPrevious: builtins.bytes
    networkTime: builtins.int
    firstSeq: builtins.int
    lastSeq: builtins.int
    def __init__(
        self,
        *,
        newStatus: global___NodeStatus.ValueType | None = ...,
        newEvent: global___NodeEvent.ValueType | None = ...,
        ledgerSeq: builtins.int | None = ...,
        ledgerHash: builtins.bytes | None = ...,
        ledgerHashPrevious: builtins.bytes | None = ...,
        networkTime: builtins.int | None = ...,
        firstSeq: builtins.int | None = ...,
        lastSeq: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["firstSeq", b"firstSeq", "lastSeq", b"lastSeq", "ledgerHash", b"ledgerHash", "ledgerHashPrevious", b"ledgerHashPrevious", "ledgerSeq", b"ledgerSeq", "networkTime", b"networkTime", "newEvent", b"newEvent", "newStatus", b"newStatus"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["firstSeq", b"firstSeq", "lastSeq", b"lastSeq", "ledgerHash", b"ledgerHash", "ledgerHashPrevious", b"ledgerHashPrevious", "ledgerSeq", b"ledgerSeq", "networkTime", b"networkTime", "newEvent", b"newEvent", "newStatus", b"newStatus"]) -> None: ...

global___TMStatusChange = TMStatusChange

@typing.final
class TMProposeSet(google.protobuf.message.Message):
    """Announce to the network our position on a closing ledger"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROPOSESEQ_FIELD_NUMBER: builtins.int
    CURRENTTXHASH_FIELD_NUMBER: builtins.int
    NODEPUBKEY_FIELD_NUMBER: builtins.int
    CLOSETIME_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    PREVIOUSLEDGER_FIELD_NUMBER: builtins.int
    ADDEDTRANSACTIONS_FIELD_NUMBER: builtins.int
    REMOVEDTRANSACTIONS_FIELD_NUMBER: builtins.int
    CHECKEDSIGNATURE_FIELD_NUMBER: builtins.int
    HOPS_FIELD_NUMBER: builtins.int
    proposeSeq: builtins.int
    currentTxHash: builtins.bytes
    """the hash of the ledger we are proposing"""
    nodePubKey: builtins.bytes
    closeTime: builtins.int
    signature: builtins.bytes
    """signature of above fields"""
    previousledger: builtins.bytes
    checkedSignature: builtins.bool
    """node vouches signature is correct"""
    hops: builtins.int
    """Number of hops traveled"""
    @property
    def addedTransactions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """not required if number is large"""

    @property
    def removedTransactions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """not required if number is large"""

    def __init__(
        self,
        *,
        proposeSeq: builtins.int | None = ...,
        currentTxHash: builtins.bytes | None = ...,
        nodePubKey: builtins.bytes | None = ...,
        closeTime: builtins.int | None = ...,
        signature: builtins.bytes | None = ...,
        previousledger: builtins.bytes | None = ...,
        addedTransactions: collections.abc.Iterable[builtins.bytes] | None = ...,
        removedTransactions: collections.abc.Iterable[builtins.bytes] | None = ...,
        checkedSignature: builtins.bool | None = ...,
        hops: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["checkedSignature", b"checkedSignature", "closeTime", b"closeTime", "currentTxHash", b"currentTxHash", "hops", b"hops", "nodePubKey", b"nodePubKey", "previousledger", b"previousledger", "proposeSeq", b"proposeSeq", "signature", b"signature"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["addedTransactions", b"addedTransactions", "checkedSignature", b"checkedSignature", "closeTime", b"closeTime", "currentTxHash", b"currentTxHash", "hops", b"hops", "nodePubKey", b"nodePubKey", "previousledger", b"previousledger", "proposeSeq", b"proposeSeq", "removedTransactions", b"removedTransactions", "signature", b"signature"]) -> None: ...

global___TMProposeSet = TMProposeSet

@typing.final
class TMHaveTransactionSet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    status: global___TxSetStatus.ValueType
    hash: builtins.bytes
    def __init__(
        self,
        *,
        status: global___TxSetStatus.ValueType | None = ...,
        hash: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["hash", b"hash", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["hash", b"hash", "status", b"status"]) -> None: ...

global___TMHaveTransactionSet = TMHaveTransactionSet

@typing.final
class TMValidatorList(google.protobuf.message.Message):
    """Validator list (UNL)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MANIFEST_FIELD_NUMBER: builtins.int
    BLOB_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    manifest: builtins.bytes
    blob: builtins.bytes
    signature: builtins.bytes
    version: builtins.int
    def __init__(
        self,
        *,
        manifest: builtins.bytes | None = ...,
        blob: builtins.bytes | None = ...,
        signature: builtins.bytes | None = ...,
        version: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["blob", b"blob", "manifest", b"manifest", "signature", b"signature", "version", b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["blob", b"blob", "manifest", b"manifest", "signature", b"signature", "version", b"version"]) -> None: ...

global___TMValidatorList = TMValidatorList

@typing.final
class ValidatorBlobInfo(google.protobuf.message.Message):
    """Validator List v2"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MANIFEST_FIELD_NUMBER: builtins.int
    BLOB_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    manifest: builtins.bytes
    blob: builtins.bytes
    signature: builtins.bytes
    def __init__(
        self,
        *,
        manifest: builtins.bytes | None = ...,
        blob: builtins.bytes | None = ...,
        signature: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["blob", b"blob", "manifest", b"manifest", "signature", b"signature"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["blob", b"blob", "manifest", b"manifest", "signature", b"signature"]) -> None: ...

global___ValidatorBlobInfo = ValidatorBlobInfo

@typing.final
class TMValidatorListCollection(google.protobuf.message.Message):
    """Collection of Validator List v2 (UNL)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    MANIFEST_FIELD_NUMBER: builtins.int
    BLOBS_FIELD_NUMBER: builtins.int
    version: builtins.int
    manifest: builtins.bytes
    @property
    def blobs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ValidatorBlobInfo]: ...
    def __init__(
        self,
        *,
        version: builtins.int | None = ...,
        manifest: builtins.bytes | None = ...,
        blobs: collections.abc.Iterable[global___ValidatorBlobInfo] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["manifest", b"manifest", "version", b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["blobs", b"blobs", "manifest", b"manifest", "version", b"version"]) -> None: ...

global___TMValidatorListCollection = TMValidatorListCollection

@typing.final
class TMValidation(google.protobuf.message.Message):
    """Used to sign a final closed ledger after reprocessing"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALIDATION_FIELD_NUMBER: builtins.int
    CHECKEDSIGNATURE_FIELD_NUMBER: builtins.int
    HOPS_FIELD_NUMBER: builtins.int
    validation: builtins.bytes
    """The serialized validation"""
    checkedSignature: builtins.bool
    """node vouches signature is correct"""
    hops: builtins.int
    """Number of hops traveled"""
    def __init__(
        self,
        *,
        validation: builtins.bytes | None = ...,
        checkedSignature: builtins.bool | None = ...,
        hops: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["checkedSignature", b"checkedSignature", "hops", b"hops", "validation", b"validation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["checkedSignature", b"checkedSignature", "hops", b"hops", "validation", b"validation"]) -> None: ...

global___TMValidation = TMValidation

@typing.final
class TMEndpoints(google.protobuf.message.Message):
    """An array of Endpoint messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TMEndpointv2(google.protobuf.message.Message):
        """An update to the Endpoint type that uses a string
        to represent endpoints, thus allowing ipv6 or ipv4 addresses
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ENDPOINT_FIELD_NUMBER: builtins.int
        HOPS_FIELD_NUMBER: builtins.int
        endpoint: builtins.str
        hops: builtins.int
        def __init__(
            self,
            *,
            endpoint: builtins.str | None = ...,
            hops: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["endpoint", b"endpoint", "hops", b"hops"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["endpoint", b"endpoint", "hops", b"hops"]) -> None: ...

    VERSION_FIELD_NUMBER: builtins.int
    ENDPOINTS_V2_FIELD_NUMBER: builtins.int
    version: builtins.int
    """This field is used to allow the TMEndpoints message format to be
    modified as necessary in the future.
    """
    @property
    def endpoints_v2(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TMEndpoints.TMEndpointv2]: ...
    def __init__(
        self,
        *,
        version: builtins.int | None = ...,
        endpoints_v2: collections.abc.Iterable[global___TMEndpoints.TMEndpointv2] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["version", b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["endpoints_v2", b"endpoints_v2", "version", b"version"]) -> None: ...

global___TMEndpoints = TMEndpoints

@typing.final
class TMIndexedObject(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HASH_FIELD_NUMBER: builtins.int
    NODEID_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    LEDGERSEQ_FIELD_NUMBER: builtins.int
    hash: builtins.bytes
    nodeID: builtins.bytes
    index: builtins.bytes
    data: builtins.bytes
    ledgerSeq: builtins.int
    def __init__(
        self,
        *,
        hash: builtins.bytes | None = ...,
        nodeID: builtins.bytes | None = ...,
        index: builtins.bytes | None = ...,
        data: builtins.bytes | None = ...,
        ledgerSeq: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data", "hash", b"hash", "index", b"index", "ledgerSeq", b"ledgerSeq", "nodeID", b"nodeID"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "hash", b"hash", "index", b"index", "ledgerSeq", b"ledgerSeq", "nodeID", b"nodeID"]) -> None: ...

global___TMIndexedObject = TMIndexedObject

@typing.final
class TMGetObjectByHash(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ObjectType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ObjectTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TMGetObjectByHash._ObjectType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        otUNKNOWN: TMGetObjectByHash._ObjectType.ValueType  # 0
        otLEDGER: TMGetObjectByHash._ObjectType.ValueType  # 1
        otTRANSACTION: TMGetObjectByHash._ObjectType.ValueType  # 2
        otTRANSACTION_NODE: TMGetObjectByHash._ObjectType.ValueType  # 3
        otSTATE_NODE: TMGetObjectByHash._ObjectType.ValueType  # 4
        otCAS_OBJECT: TMGetObjectByHash._ObjectType.ValueType  # 5
        otFETCH_PACK: TMGetObjectByHash._ObjectType.ValueType  # 6

    class ObjectType(_ObjectType, metaclass=_ObjectTypeEnumTypeWrapper): ...
    otUNKNOWN: TMGetObjectByHash.ObjectType.ValueType  # 0
    otLEDGER: TMGetObjectByHash.ObjectType.ValueType  # 1
    otTRANSACTION: TMGetObjectByHash.ObjectType.ValueType  # 2
    otTRANSACTION_NODE: TMGetObjectByHash.ObjectType.ValueType  # 3
    otSTATE_NODE: TMGetObjectByHash.ObjectType.ValueType  # 4
    otCAS_OBJECT: TMGetObjectByHash.ObjectType.ValueType  # 5
    otFETCH_PACK: TMGetObjectByHash.ObjectType.ValueType  # 6

    TYPE_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    SEQ_FIELD_NUMBER: builtins.int
    LEDGERHASH_FIELD_NUMBER: builtins.int
    FAT_FIELD_NUMBER: builtins.int
    OBJECTS_FIELD_NUMBER: builtins.int
    type: global___TMGetObjectByHash.ObjectType.ValueType
    query: builtins.bool
    """is this a query or a reply?"""
    seq: builtins.int
    """used to match replies to queries"""
    ledgerHash: builtins.bytes
    """the hash of the ledger these queries are for"""
    fat: builtins.bool
    """return related nodes"""
    @property
    def objects(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TMIndexedObject]:
        """the specific objects requested"""

    def __init__(
        self,
        *,
        type: global___TMGetObjectByHash.ObjectType.ValueType | None = ...,
        query: builtins.bool | None = ...,
        seq: builtins.int | None = ...,
        ledgerHash: builtins.bytes | None = ...,
        fat: builtins.bool | None = ...,
        objects: collections.abc.Iterable[global___TMIndexedObject] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fat", b"fat", "ledgerHash", b"ledgerHash", "query", b"query", "seq", b"seq", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fat", b"fat", "ledgerHash", b"ledgerHash", "objects", b"objects", "query", b"query", "seq", b"seq", "type", b"type"]) -> None: ...

global___TMGetObjectByHash = TMGetObjectByHash

@typing.final
class TMLedgerNode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODEDATA_FIELD_NUMBER: builtins.int
    NODEID_FIELD_NUMBER: builtins.int
    nodedata: builtins.bytes
    nodeid: builtins.bytes
    """missing for ledger base data"""
    def __init__(
        self,
        *,
        nodedata: builtins.bytes | None = ...,
        nodeid: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["nodedata", b"nodedata", "nodeid", b"nodeid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["nodedata", b"nodedata", "nodeid", b"nodeid"]) -> None: ...

global___TMLedgerNode = TMLedgerNode

@typing.final
class TMGetLedger(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITYPE_FIELD_NUMBER: builtins.int
    LTYPE_FIELD_NUMBER: builtins.int
    LEDGERHASH_FIELD_NUMBER: builtins.int
    LEDGERSEQ_FIELD_NUMBER: builtins.int
    NODEIDS_FIELD_NUMBER: builtins.int
    REQUESTCOOKIE_FIELD_NUMBER: builtins.int
    QUERYTYPE_FIELD_NUMBER: builtins.int
    QUERYDEPTH_FIELD_NUMBER: builtins.int
    itype: global___TMLedgerInfoType.ValueType
    ltype: global___TMLedgerType.ValueType
    ledgerHash: builtins.bytes
    """Can also be the transaction set hash if liTS_CANDIDATE"""
    ledgerSeq: builtins.int
    requestCookie: builtins.int
    queryType: global___TMQueryType.ValueType
    queryDepth: builtins.int
    """How deep to go, number of extra levels"""
    @property
    def nodeIDs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        itype: global___TMLedgerInfoType.ValueType | None = ...,
        ltype: global___TMLedgerType.ValueType | None = ...,
        ledgerHash: builtins.bytes | None = ...,
        ledgerSeq: builtins.int | None = ...,
        nodeIDs: collections.abc.Iterable[builtins.bytes] | None = ...,
        requestCookie: builtins.int | None = ...,
        queryType: global___TMQueryType.ValueType | None = ...,
        queryDepth: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["itype", b"itype", "ledgerHash", b"ledgerHash", "ledgerSeq", b"ledgerSeq", "ltype", b"ltype", "queryDepth", b"queryDepth", "queryType", b"queryType", "requestCookie", b"requestCookie"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["itype", b"itype", "ledgerHash", b"ledgerHash", "ledgerSeq", b"ledgerSeq", "ltype", b"ltype", "nodeIDs", b"nodeIDs", "queryDepth", b"queryDepth", "queryType", b"queryType", "requestCookie", b"requestCookie"]) -> None: ...

global___TMGetLedger = TMGetLedger

@typing.final
class TMLedgerData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEDGERHASH_FIELD_NUMBER: builtins.int
    LEDGERSEQ_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    NODES_FIELD_NUMBER: builtins.int
    REQUESTCOOKIE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ledgerHash: builtins.bytes
    ledgerSeq: builtins.int
    type: global___TMLedgerInfoType.ValueType
    requestCookie: builtins.int
    error: global___TMReplyError.ValueType
    @property
    def nodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TMLedgerNode]: ...
    def __init__(
        self,
        *,
        ledgerHash: builtins.bytes | None = ...,
        ledgerSeq: builtins.int | None = ...,
        type: global___TMLedgerInfoType.ValueType | None = ...,
        nodes: collections.abc.Iterable[global___TMLedgerNode] | None = ...,
        requestCookie: builtins.int | None = ...,
        error: global___TMReplyError.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error", "ledgerHash", b"ledgerHash", "ledgerSeq", b"ledgerSeq", "requestCookie", b"requestCookie", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "ledgerHash", b"ledgerHash", "ledgerSeq", b"ledgerSeq", "nodes", b"nodes", "requestCookie", b"requestCookie", "type", b"type"]) -> None: ...

global___TMLedgerData = TMLedgerData

@typing.final
class TMPing(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _pingType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _pingTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TMPing._pingType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ptPING: TMPing._pingType.ValueType  # 0
        """we want a reply"""
        ptPONG: TMPing._pingType.ValueType  # 1
        """this is a reply"""

    class pingType(_pingType, metaclass=_pingTypeEnumTypeWrapper): ...
    ptPING: TMPing.pingType.ValueType  # 0
    """we want a reply"""
    ptPONG: TMPing.pingType.ValueType  # 1
    """this is a reply"""

    TYPE_FIELD_NUMBER: builtins.int
    SEQ_FIELD_NUMBER: builtins.int
    PINGTIME_FIELD_NUMBER: builtins.int
    NETTIME_FIELD_NUMBER: builtins.int
    type: global___TMPing.pingType.ValueType
    seq: builtins.int
    """detect stale replies, ensure other side is reading"""
    pingTime: builtins.int
    """know when we think we sent the ping"""
    netTime: builtins.int
    def __init__(
        self,
        *,
        type: global___TMPing.pingType.ValueType | None = ...,
        seq: builtins.int | None = ...,
        pingTime: builtins.int | None = ...,
        netTime: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["netTime", b"netTime", "pingTime", b"pingTime", "seq", b"seq", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["netTime", b"netTime", "pingTime", b"pingTime", "seq", b"seq", "type", b"type"]) -> None: ...

global___TMPing = TMPing

@typing.final
class TMSquelch(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SQUELCH_FIELD_NUMBER: builtins.int
    VALIDATORPUBKEY_FIELD_NUMBER: builtins.int
    SQUELCHDURATION_FIELD_NUMBER: builtins.int
    squelch: builtins.bool
    """squelch if true, otherwise unsquelch"""
    validatorPubKey: builtins.bytes
    """validator's public key"""
    squelchDuration: builtins.int
    """squelch duration in seconds"""
    def __init__(
        self,
        *,
        squelch: builtins.bool | None = ...,
        validatorPubKey: builtins.bytes | None = ...,
        squelchDuration: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["squelch", b"squelch", "squelchDuration", b"squelchDuration", "validatorPubKey", b"validatorPubKey"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["squelch", b"squelch", "squelchDuration", b"squelchDuration", "validatorPubKey", b"validatorPubKey"]) -> None: ...

global___TMSquelch = TMSquelch

@typing.final
class TMProofPathRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    LEDGERHASH_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    ledgerHash: builtins.bytes
    type: global___TMLedgerMapType.ValueType
    def __init__(
        self,
        *,
        key: builtins.bytes | None = ...,
        ledgerHash: builtins.bytes | None = ...,
        type: global___TMLedgerMapType.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["key", b"key", "ledgerHash", b"ledgerHash", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "ledgerHash", b"ledgerHash", "type", b"type"]) -> None: ...

global___TMProofPathRequest = TMProofPathRequest

@typing.final
class TMProofPathResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    LEDGERHASH_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LEDGERHEADER_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    ledgerHash: builtins.bytes
    type: global___TMLedgerMapType.ValueType
    ledgerHeader: builtins.bytes
    error: global___TMReplyError.ValueType
    @property
    def path(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        key: builtins.bytes | None = ...,
        ledgerHash: builtins.bytes | None = ...,
        type: global___TMLedgerMapType.ValueType | None = ...,
        ledgerHeader: builtins.bytes | None = ...,
        path: collections.abc.Iterable[builtins.bytes] | None = ...,
        error: global___TMReplyError.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error", "key", b"key", "ledgerHash", b"ledgerHash", "ledgerHeader", b"ledgerHeader", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "key", b"key", "ledgerHash", b"ledgerHash", "ledgerHeader", b"ledgerHeader", "path", b"path", "type", b"type"]) -> None: ...

global___TMProofPathResponse = TMProofPathResponse

@typing.final
class TMReplayDeltaRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEDGERHASH_FIELD_NUMBER: builtins.int
    ledgerHash: builtins.bytes
    def __init__(
        self,
        *,
        ledgerHash: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ledgerHash", b"ledgerHash"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ledgerHash", b"ledgerHash"]) -> None: ...

global___TMReplayDeltaRequest = TMReplayDeltaRequest

@typing.final
class TMReplayDeltaResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEDGERHASH_FIELD_NUMBER: builtins.int
    LEDGERHEADER_FIELD_NUMBER: builtins.int
    TRANSACTION_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ledgerHash: builtins.bytes
    ledgerHeader: builtins.bytes
    error: global___TMReplyError.ValueType
    @property
    def transaction(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        ledgerHash: builtins.bytes | None = ...,
        ledgerHeader: builtins.bytes | None = ...,
        transaction: collections.abc.Iterable[builtins.bytes] | None = ...,
        error: global___TMReplyError.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error", "ledgerHash", b"ledgerHash", "ledgerHeader", b"ledgerHeader"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "ledgerHash", b"ledgerHash", "ledgerHeader", b"ledgerHeader", "transaction", b"transaction"]) -> None: ...

global___TMReplayDeltaResponse = TMReplayDeltaResponse
