FROM docker:cli AS dockercli

FROM python:3.12-bookworm

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /tmp/rocket-debug-build

COPY requirements.txt .

COPY --from=dockercli /usr/local/bin/docker /usr/local/bin/docker

RUN cat <<'EOF' >> /etc/bash.bashrc

# rocket-debug-shell
export CLICOLOR=1
export LS_COLORS="${LS_COLORS:-rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32}"
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
EOF

RUN python -m pip install -U pip wheel setuptools \
    && pip install -r requirements.txt

CMD ["bash"]
