FROM python:3.12-bookworm

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /tmp/rocket-debug-build

COPY requirements.txt .

RUN python -m pip install -U pip wheel setuptools \
    && pip install -r requirements.txt

CMD ["bash"]
