min_priority: 1
max_priority: 100
# dispatch_interval_ms: 20
target_inbox: 10
overflow_factor: 1.2
underflow_factor: 0.8
sensitivity_ratio: 1.2
min_packets_per_second: 100
max_events: 1000

encoding: []


# Message type priorities configuration
# Lower number priority is sent first
#priority_list:
#  30: 74 # ripple_pb2.TMTransaction
#  31: 29 # ripple_pb2.TMGetLedger
#  32: 81 # ripple_pb2.TMLedgerData
#  33: 38 # ripple_pb2.TMProposeSet
#  34: 45 # ripple_pb2.TMStatusChange
#  35: 66 # ripple_pb2.TMHaveTransactionSet
#  41: 51 # ripple_pb2.TMValidation